image: maven:3.9-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - build

build-job:
  stage: build
  script:
    - cd "Code Java/Trackr"
    - mvn clean package -DskipTests
    - cp target/trackr-app-*.jar ../../trackr-app.jar
  artifacts:
    name: "Trackr-App-$CI_COMMIT_SHORT_SHA"
    paths:
      - trackr-app.jar
    expire_in: 1 day
