image: maven:3.9-eclipse-temurin-17

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

stages:
  - test
  - build

test-job:
  stage: test
  script:
    - cd "Code Java/Trackr"
    - mvn test

build-job:
  stage: build
  script:
    - cd "Code Java/Trackr"
    - mvn clean package -DskipTests
    - cp target/trackr-app-*.jar ../../trackr-app.jar
  artifacts:
    name: "Trackr-App"
    paths:
      - trackr-app.jar
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "master"
