site_name: Trackr - Documentation officielle
site_description: Documentation complète du projet Trackr (SAE-DEV)
site_author: Équipe Trackr

theme:
  name: material
  language: fr
  icon:
    logo: material/movie-open-play
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Accueil: index.md
  - 📂 Rendus du projet:
      - Rendu 1: Documents et Rendus/Rendu 1/rendu1.md
      - Rendu 2: Documents et Rendus/Rendu 2/rendu2.md
  - 🛠️ Guide de contribution: CONTRIBUTING.md
  - 🕒 Historique: CHANGELOG.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
