image: maven:3.9.6-eclipse-temurin-17

stages:
  - build

build-job:
  stage: build
  script:
    - cd Trackr
    - mvn package
  artifacts:
    paths:
      - Trackr/target/*.jar
    expire_in: 1 week
